# Generated by Django 2.1.4 on 2019-03-26 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booksinstance',
            options={'ordering': ['date_back'], 'permissions': (('can_mark_returned', 'Set Books as Returned'),)},
        ),
        migrations.AddField(
            model_name='booksinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
